name: Deploy API JAR

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build Backend API JAR and Echo Message
        run: |
          ./gradlew :backend:build
          echo "YES"

      - name: Get secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2.0.1
        with:
          secret-ids: SM, ${{ vars.AWS_SECRET_NAME_API }}
          parse-json-secrets: true

      - name: Fetch Parameter from SSM Parameter Store
        run: |
             ${{env.EC2_SSH_PRIVATE_KEY}}=$(aws ssm get-parameter --name  ${{ env.SM_KEYID}} --with-decryption --query "Parameter.Value" --output text)

      - name: Copy JAR to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SM_INSTANCEIP }}
          username: "ec2-user"
          key: ${{ env.EC2_SSH_PRIVATE_KEY}}
          port: 22
          source: "backend/build/libs/backend-1.0-SNAPSHOT.jar"
          target: "backend-1.0-SNAPSHOT.jar"
        