on:
  push:
    branches: [feature/actions]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: manual approve
        run: |
          echo "Manually approved"
    
